const mongoose=require('mongoose')

const ProfileSchema=new mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user'
    },
    company:{
        type:String
    },
    location:{
        type:String
    },
  
    status:{
        type:String,
        required:true
    },
    skills:{
        type:[String],
        required:true
    },
    bio:{
        type:String
    },
    github:{
        type:String,
    },
    experience:[
        {
            title:{
                type:String,
                required:true
            },
            company:{
                type:String,
                required:true
            },
            location:{
                type:String,
            },
            from:{
                type:Date,
                required:true
            },
            to:{
                type:String,
            },
            current:{
                type:Boolean,
                default:false
            },
            decription:{
                type:String,
            },
        }
    ],
    education:[
        {
            school:{
                type:String,
                required:true
            },
            degree:{
                type:String,
                required:true
            },
            from:{
                type:Date,
                required:true
            },
            to:{
                type:Date,
                required:true
            },
            current:{
                type:Boolean,
                default:false
            },
            decription:{
                type:String,
            },
        }
    ],
    social:
        {
            instagram:{
                type:String,
            },
            linkedin:{
                type:String
            },
            facebook:{
                type:String
            }
        
        },
        date:{
            type:Date,
            default:Date.now
        }
    
})

module.exports=Profile=mongoose.model('profile',ProfileSchema);
